// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type UserConnection struct {
	Edges      []*UserEdge `json:"edges"`
	PageInfo   *PageInfo   `json:"pageInfo"`
	TotalCount int32       `json:"totalCount"`
}

type UserEdge struct {
	Cursor string `json:"cursor"`
	Node   *User  `json:"node"`
}

type CommentOrder string

const (
	CommentOrderNewest CommentOrder = "NEWEST"
	CommentOrderOldest CommentOrder = "OLDEST"
)

var AllCommentOrder = []CommentOrder{
	CommentOrderNewest,
	CommentOrderOldest,
}

func (e CommentOrder) IsValid() bool {
	switch e {
	case CommentOrderNewest, CommentOrderOldest:
		return true
	}
	return false
}

func (e CommentOrder) String() string {
	return string(e)
}

func (e *CommentOrder) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CommentOrder(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CommentOrder", str)
	}
	return nil
}

func (e CommentOrder) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CommentOrder) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CommentOrder) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
