package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/RoGogDBD/GQLGo/internal/models"
	"github.com/RoGogDBD/GQLGo/internal/utils/graph"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input models.CreatePostInput) (*models.Post, error) {
	return r.PostRepo.Create(ctx, input)
}

// SetCommentsEnabled is the resolver for the setCommentsEnabled field.
func (r *mutationResolver) SetCommentsEnabled(ctx context.Context, postID string, enabled bool) (*models.Post, error) {
	return r.PostRepo.SetCommentsEnabled(ctx, postID, enabled)
}

// AddComment is the resolver for the addComment field.
func (r *mutationResolver) AddComment(ctx context.Context, input models.AddCommentInput) (*models.Comment, error) {
	return nil, fmt.Errorf("not implemented: AddComment - addComment")
}

// GetPosts is the resolver for the GetPosts field.
func (r *queryResolver) GetPosts(ctx context.Context, first *int32, after *string) (*models.PostConnection, error) {
	f := int32(20)
	if first != nil {
		f = *first
	}
	list, endCursor, err := r.PostRepo.List(ctx, f, after)
	if err != nil {
		return nil, err
	}
	return graph.NewPostConnection(list, endCursor), nil
}

// GetPost is the resolver for the GetPost field.
func (r *queryResolver) GetPost(ctx context.Context, id string) (*models.Post, error) {
	return r.PostRepo.GetByID(ctx, id)
}

// GetUsers is the resolver for the GetUsers field.
func (r *queryResolver) GetUsers(ctx context.Context, first *int32, after *string) (*models.UserConnection, error) {
	f := int32(20)
	if first != nil {
		f = *first
	}
	list, endCursor, err := r.UserRepo.List(ctx, f, after)
	if err != nil {
		return nil, err
	}
	return graph.NewUserConnection(list, endCursor), nil
}

// GetUser is the resolver for the GetUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*models.User, error) {
	return r.UserRepo.GetByID(ctx, id)
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID string) (<-chan *models.Comment, error) {
	return nil, fmt.Errorf("not implemented: CommentAdded - commentAdded")
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
